import ereignisseNachvollziehen from "./notizen/portal/2026-09-06-ereignisse-nachvollziehen";
import zeichenVoruebergehendPausiert from "./notizen/portal/2026-09-07-zeichen-voruebergehend-pausiert";
import versionsnummerImProfil from "./notizen/portal/2026-09-08-versionsnummer-im-profil";
import type { Releasenotiz } from "@/app/m/portal/_lib/neuigkeiten/typen";

import anleitungJeAnsicht from "@/app/m/portal/_lib/neuigkeiten/notizen/aufgaben/2026-08-16-anleitung-je-ansicht";
import verteilenZweiAnsichten from "@/app/m/portal/_lib/neuigkeiten/notizen/aufgaben/2026-08-16-verteilen-zwei-ansichten";
import checklisteAlsPdf from "@/app/m/portal/_lib/neuigkeiten/notizen/lagerbuch/2026-08-16-checkliste-als-pdf";
import mitCodeEinsteigen from "@/app/m/portal/_lib/neuigkeiten/notizen/lagerbuch/2026-09-13-mit-code-einsteigen";
import bestandNullAusblenden from "@/app/m/portal/_lib/neuigkeiten/notizen/lagerbuch/2026-09-13-bestand-null-ausblenden";
import checklisteVerfallLeer from "@/app/m/portal/_lib/neuigkeiten/notizen/lagerbuch/2026-09-14-checkliste-verfall-leer";
import kategorienAusblenden from "@/app/m/portal/_lib/neuigkeiten/notizen/lagerbuch/2026-09-14-kategorien-ausblenden";
import inventurJeCharge from "@/app/m/portal/_lib/neuigkeiten/notizen/lagerbuch/2026-09-14-inventur-je-charge";
import mehrereArtikelBearbeiten from "@/app/m/portal/_lib/neuigkeiten/notizen/lagerbuch/2026-09-14-mehrere-artikel-bearbeiten";
import journalNachladen from "@/app/m/portal/_lib/neuigkeiten/notizen/lagerbuch/2026-09-14-journal-nachladen";
import aussondernAmFahrzeug from "@/app/m/portal/_lib/neuigkeiten/notizen/lagerbuch/2026-09-15-aussondern-am-fahrzeug";
import abgelaufenesJeFahrzeug from "@/app/m/portal/_lib/neuigkeiten/notizen/lagerbuch/2026-09-15-abgelaufenes-je-fahrzeug";
import checkNurFuerDeinFahrzeug from "@/app/m/portal/_lib/neuigkeiten/notizen/lagerbuch/2026-09-15-check-nur-fuer-dein-fahrzeug";
import entnahmeAufsFahrzeug from "@/app/m/portal/_lib/neuigkeiten/notizen/lagerbuch/2026-09-15-entnahme-aufs-fahrzeug";
import letzterCheckUndVerfallLoeschen from "@/app/m/portal/_lib/neuigkeiten/notizen/lagerbuch/2026-09-15-letzter-check-und-verfall-loeschen";
import mengenSelbstZaehlen from "@/app/m/portal/_lib/neuigkeiten/notizen/lagerbuch/2026-09-15-mengen-selbst-zaehlen";
import sauerstoffWechselhinweis from "@/app/m/portal/_lib/neuigkeiten/notizen/lagerbuch/2026-09-15-sauerstoff-wechselhinweis";